### ISSUE TITLE
Clip radio button example

### ISSUE THREAD

**Issue by MichielBijl** [notabene/accessibilitytests#1]
This works:

```HTML
<label>
	<input type="radio">
	<span>Le label</span>
</label>
```

```CSS
label {
  position: relative;
  overflow: hidden;
}

[type="radio"] {
  position: absolute;
  right: 100%;
  clip: rect(0, 0, 0, 0);
}

[type="radio"]:focus + span {
  outline: 3px solid royalblue;
}
```
